/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class verkle_cryptography_LibIpaMultipoint */

#ifndef _Included_verkle_cryptography_LibIpaMultipoint
#define _Included_verkle_cryptography_LibIpaMultipoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     verkle_cryptography_LibIpaMultipoint
 * Method:    commit
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_verkle_cryptography_LibIpaMultipoint_commit
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     verkle_cryptography_LibIpaMultipoint
 * Method:    addCommitment
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_verkle_cryptography_LibIpaMultipoint_addCommitment
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     verkle_cryptography_LibIpaMultipoint
 * Method:    commitAsCompressed
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_verkle_cryptography_LibIpaMultipoint_commitAsCompressed
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     verkle_cryptography_LibIpaMultipoint
 * Method:    updateSparse
 * Signature: ([B[B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_verkle_cryptography_LibIpaMultipoint_updateSparse
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     verkle_cryptography_LibIpaMultipoint
 * Method:    compress
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_verkle_cryptography_LibIpaMultipoint_compress
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     verkle_cryptography_LibIpaMultipoint
 * Method:    compressMany
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_verkle_cryptography_LibIpaMultipoint_compressMany
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     verkle_cryptography_LibIpaMultipoint
 * Method:    hash
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_verkle_cryptography_LibIpaMultipoint_hash
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     verkle_cryptography_LibIpaMultipoint
 * Method:    hashMany
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_verkle_cryptography_LibIpaMultipoint_hashMany
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     verkle_cryptography_LibIpaMultipoint
 * Method:    verifyPreStateRoot
 * Signature: ([[B[[B[[B[[B[[B[[B[B[B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_verkle_cryptography_LibIpaMultipoint_verifyPreStateRoot
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
